# landscape short name
landscapeName: RISC-V 
# Update with your membership structure
landscapeMemberClasses:
  - name: Premier 250k
    category: Premier
  - name: Premier 100k
    category: Premier 
  - name: Strategic Membership
    category: Strategic
  - name: Start-up Strategic Membership
    category: Strategic    
  - name: Community Membership
    category: Community
# SF Project record ID for your project
project: a092M00001JV3GBQA1 # RISC-V
# Name of category for members 
landscapeMemberCategory: RISC-V Members
