# landscape short name
landscapeName: RISC-V 
# Update with your membership structure
landscapeMemberClasses:
  - name: Premier Member
    category: Premier
  - name: Premier TSC Member
    category: Premier TSC
  - name: Strategic Member
    category: Strategic
  - name: Community Member
    category: Community
# SF Project record ID for your project
project: a092M00001JV3GBQA1 # RISC-V
# Name of category for members 
landscapeMemberCategory: RISC-V Members
